[package]
name = "hpp_rust"
version = "0.1.0"
edition = "2021"

[dependencies]
nalgebra = "0.33.2"
rand = "0.8.5"
rand_distr = "0.4.3"
statrs = "0.17.1"

hawklib = { path = "../hawklib"}
prettytable = "0.10.0"
