[package]
name = "hpp_rust"
version = "0.1.0"
edition = "2021"

[dependencies]
nalgebra = "0.33.2"
rand = "0.8.5"
rand_distr = "0.4.3"
statrs = "0.17.1"

hawklib = { path = "../hawklib"}
prettytable = "0.10.0"
peak_alloc = "0.2.1"
bincode = "1.3.3"
rayon = "1.10.0"
indicatif = "0.17.9"
