[package]
name = "hawk_rust"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sha3 = "0.10.1"
rand = "0.8"
rand_core = "0.6"
prime_factorization = "1.0.4"
num = "0.4"

num-bigint = "0.4"
